name = "Piece of Peace"
author = "Aproxia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c340ce8c72af2908d508302340f15d0450e51455681bdf52ca2cbc29d15b7084"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
